server:
  port: 8080
wx-config:
  appId: ***********
  appSecret: ***********
  checkToken: ***********

chatgpt-config:
  model: text-davinci-003
  temperature: 0.9
  maxTokens: 512
  apiKey: ***********
